version: '3.9'

services:
  # server:
  #   build: ./mern/server
  #   image: mern-server
  #   container_name: projet_si_et_donnes_mern_node_server
  #   command: npm run dev
  #   volumes:
  #     - ./mern/server/:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo
  #   env_file: ./mern/server/.env
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network
  # mongo:
  #   image: mongo:latest
  #   container_name: projet_si_et_donnes_mern_mongo_db
  #   environment:
  #     MONGO_INITDB_DATABASE: clother
  #   volumes:
  #     - ./mern/db/data-volume:/data/db
  #     - ./mern/db/cloths.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - app-network
  # client:
  #   build: ./mern/client
  #   image: mern-client
  #   container_name: projet_si_et_donnes_mern_react_client
  #   command: npm run start
  #   volumes:
  #     - ./mern/client/:/usr/app
  #     - /usr/app/node_modules
  #   depends_on:
  #     - server
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network
  # ml:
  #   container_name: projet_si_et_donnes_ml
  #   build: ./ml
  #   environment:
  #     FLASK_DEBUG: 1
  #   volumes:
  #     - ./ml:/app
  #     - D:\Cours\ML\clother\data\LaHalle:/data
  #   ports:
  #     - 5000:5000
  #   restart: always
  #   networks:
  #     - app-network
  kaggle_ml:
    container_name: kaggle_ml
    build: ./kaggle
    volumes:
      - ./kaggle:/app
      - D:\imaterialist-fashion-2019-FGVC6:/data
    restart: always
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local